## Hyperprameter tuning and cross validation

In [1]:
import pandas as pd
df=pd.read_csv('Cars93.csv')
df.head()

id Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0   1        Acura  Integra    Small       12.9   15.9       18.8        25   
1   2        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2   3         Audi       90  Compact       25.9   29.1       32.3        20   
3   4         Audi      100  Midsize       30.8   37.7       44.6        19   
4   5          BMW     535i  Midsize       23.7   30.0       36.2        22   

   MPG.highway             AirBags  ... Passengers Length  Wheelbase  Width  \
0           31                 NaN  ...          5    177        102     68   
1           25  Driver & Passenger  ...          5    195        115     71   
2           26         Driver only  ...          5    180        102     67   
3           26                 NaN  ...          6    193        106     70   
4           30         Driver only  ...          4    186        109     69   

   Turn.circle  Rear.seat.room Luggage.room  Weight   Origin           Make  
0           37            26.5         11.0    2705  non-USA  Acura Integra  
1           38            30.0         15.0    3560  non-USA   Acura Legend  
2           37            28.0         14.0    3375  non-USA        Audi 90  
3           37            31.0         17.0    3405  non-USA       Audi 100  
4           39            27.0         13.0    3640  non-USA       BMW 535i  

[5 rows x 28 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  93 non-null     int64  
 1   Manufacturer        93 non-null     object 
 2   Model               93 non-null     object 
 3   Type                93 non-null     object 
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64  
 8   MPG.highway         93 non-null     int64  
 9   AirBags             56 non-null     object 
 10  DriveTrain          93 non-null     object 
 11  Cylinders           93 non-null     object 
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64  
 14  RPM                 93 non-null     int64  
 15  Rev.per.mile        93 non-null     int64  
 16  Man.trans.

## checking missing values in dataset

In [3]:
s=df.isna().sum()
s

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [4]:
s[s>0]

AirBags           37
Rear.seat.room     2
Luggage.room      11
dtype: int64

## Check Duplicates

In [5]:
df.duplicated().sum()

0

## Seperating X and Y(Weight)
Weight ~ Remaining Features

In [6]:
X = df.drop(columns=['Weight','id'])
Y = df[['Weight']]

In [7]:
X.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8        25   
1        Acura   Legend  Midsize       29.2   33.9       38.7        18   
2         Audi       90  Compact       25.9   29.1       32.3        20   
3         Audi      100  Midsize       30.8   37.7       44.6        19   
4          BMW     535i  Midsize       23.7   30.0       36.2        22   

   MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0           31                 NaN      Front  ...               13.2   
1           25  Driver & Passenger      Front  ...               18.0   
2           26         Driver only      Front  ...               16.9   
3           26                 NaN      Front  ...               21.1   
4           30         Driver only       Rear  ...               21.1   

   Passengers  Length  Wheelbase  Width Turn.circle  Rear.seat.room  \
0           5     177        102     68          37            26.5   
1           5     195        115     71          38            30.0   
2           5     180        102     67          37            28.0   
3           6     193        106     70          37            31.0   
4           4     186        109     69          39            27.0   

   Luggage.room   Origin           Make  
0          11.0  non-USA  Acura Integra  
1          15.0  non-USA   Acura Legend  
2          14.0  non-USA        Audi 90  
3          17.0  non-USA       Audi 100  
4          13.0  non-USA       BMW 535i  

[5 rows x 26 columns]

In [8]:
Y.head()

Weight
0    2705
1    3560
2    3375
3    3405
4    3640

## Perform cat con seperator on X

In [9]:
cat = list(X.columns[X.dtypes=='object'])
con = list(X.columns[X.dtypes!='object'])

In [10]:
cat

['Manufacturer',
 'Model',
 'Type',
 'AirBags',
 'DriveTrain',
 'Cylinders',
 'Man.trans.avail',
 'Origin',
 'Make']

In [11]:
con

['Min.Price',
 'Price',
 'Max.Price',
 'MPG.city',
 'MPG.highway',
 'EngineSize',
 'Horsepower',
 'RPM',
 'Rev.per.mile',
 'Fuel.tank.capacity',
 'Passengers',
 'Length',
 'Wheelbase',
 'Width',
 'Turn.circle',
 'Rear.seat.room',
 'Luggage.room']

## preprocessing pipeline for X

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [13]:
num_pipe = Pipeline(steps=[('imputer', SimpleImputer(strategy='mean')),
                           ('scaler', StandardScaler())])

cat_pipe = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                           ('ohe', OneHotEncoder(handle_unknown='ignore'))])

pre = ColumnTransformer([('num', num_pipe, con),
                         ('cat', cat_pipe, cat)])

In [14]:
X_pre = pre.fit_transform(X).toarray()
X_pre

array([[-0.48578741, -0.37572014, -0.28246529, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.38801699,  1.49784409,  1.53140881, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.00865782,  0.99822696,  0.94805231, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.66378585,  0.39452293,  0.16416702, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.53733279,  0.33207079,  0.14593713, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.88220476,  0.7484184 ,  0.60168439, ...,  0.        ,
         0.        ,  1.        ]])

In [15]:
cols = pre.get_feature_names_out()
cols

array(['num__Min.Price', 'num__Price', 'num__Max.Price', 'num__MPG.city',
       'num__MPG.highway', 'num__EngineSize', 'num__Horsepower',
       'num__RPM', 'num__Rev.per.mile', 'num__Fuel.tank.capacity',
       'num__Passengers', 'num__Length', 'num__Wheelbase', 'num__Width',
       'num__Turn.circle', 'num__Rear.seat.room', 'num__Luggage.room',
       'cat__Manufacturer_Acura', 'cat__Manufacturer_Audi',
       'cat__Manufacturer_BMW', 'cat__Manufacturer_Buick',
       'cat__Manufacturer_Cadillac', 'cat__Manufacturer_Chevrolet',
       'cat__Manufacturer_Chrylser', 'cat__Manufacturer_Chrysler',
       'cat__Manufacturer_Dodge', 'cat__Manufacturer_Eagle',
       'cat__Manufacturer_Ford', 'cat__Manufacturer_Geo',
       'cat__Manufacturer_Honda', 'cat__Manufacturer_Hyundai',
       'cat__Manufacturer_Infiniti', 'cat__Manufacturer_Lexus',
       'cat__Manufacturer_Lincoln', 'cat__Manufacturer_Mazda',
       'cat__Manufacturer_Mercedes-Benz', 'cat__Manufacturer_Mercury',
       'cat__Man

In [16]:
X_pre = pd.DataFrame(X_pre, columns=cols)
X_pre.head()

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
0       -0.485787   -0.375720       -0.282465       0.471312   
1        1.388017    1.497844        1.531409      -0.781032   
2        1.008658    0.998227        0.948052      -0.423219   
3        1.571949    1.893374        2.069191      -0.602126   
4        0.755752    1.091905        1.303535      -0.065407   

   num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
0          0.360925        -0.841022        -0.073484  1.717489   
1         -0.770514         0.515869         1.078322  0.369586   
2         -0.581941         0.128186         0.540813  0.369586   
3         -0.581941         0.128186         0.540813  0.369586   
4          0.172352         0.806631         1.231897  0.706562   

   num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
0           1.129530                -1.062184  ...                     0.0   
1           0.005661                 0.409445  ...                     0.0   
2          -0.105713                 0.072197  ...                     0.0   
3           0.410659                 1.359872  ...                     0.0   
4           0.430909                 1.359872  ...                     0.0   

   cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  cat__Make_Volvo 240  \
0                       0.0                          0.0                  0.0   
1                       0.0                          0.0                  0.0   
2                       0.0                          0.0                  0.0   
3                       0.0                          0.0                  0.0   
4                       0.0                          0.0                  0.0   

   cat__Make_Volvo 850  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  

[5 rows x 256 columns]

## Apply train test split

In [17]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_pre, Y, test_size=0.2, random_state=10)

In [18]:
xtrain.shape

(74, 256)

In [19]:
xtest.shape

(19, 256)

## Create a base linear model

In [20]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain, ytrain)

LinearRegression()

In [21]:
model.score(xtrain, ytrain)

1.0

In [22]:
model.score(xtest, ytest)

0.8492284781963767

In [23]:
from PM6func import evaluate_model
evaluate_model(xtrain, ytrain, xtest, ytest, model)

Training Results : 
MSE : 0.00
RMSE: 0.00
MAE : 0.00
R2  : 1.0000


Testing Results : 
MSE : 35029.49
RMSE: 187.16
MAE : 142.94
R2  : 0.8492


## Cross validation

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
r2_scores = cross_val_score(model, xtrain, ytrain, cv=5, scoring='r2')
r2_scores

array([0.97291899, 0.95952753, 0.88366796, 0.95863404, 0.93386159])

In [26]:
r2_cv = r2_scores.mean()
r2_cv

0.9417220227323027

## MSE cross validated

In [27]:
mse_scores = cross_val_score(model, xtrain, ytrain, cv=5, scoring='neg_mean_squared_error')
mse_scores

array([ -9849.74187082, -18581.74658785, -37653.06218208, -17787.06693959,
       -17582.59355098])

In [28]:
mse_cv = -mse_scores.mean()
mse_cv

20290.842226262226

## RMSE CV

In [29]:
rmse_scores = cross_val_score(model, xtrain, ytrain, cv=5, scoring='neg_root_mean_squared_error')
rmse_scores

array([ -99.24586576, -136.31488029, -194.04396971, -133.36816314,
       -132.59937236])

In [30]:
rmse_cv = -rmse_scores.mean()
rmse_cv

139.11445025328277

## MAE Cross validated

In [31]:
mae_scores = cross_val_score(model, xtrain, ytrain, cv=5, scoring='neg_mean_absolute_error')
mae_scores

array([ -78.11151026, -104.71030645, -157.40765753, -104.87283475,
       -101.08460797])

In [32]:
mae_cv = -mae_scores.mean()
mae_cv

109.2373833911774

##  Hyperparameter tuning

In [33]:
import numpy as np

In [34]:
params = {'alpha':np.arange(0.1,100,0.1)}
params

{'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
         1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
         2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
         3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
         4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
         5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
         6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
         7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
         8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
        10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
        11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
        12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
        13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
        14.4, 14.5, 14.6, 14.

In [35]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [36]:
rr = Ridge()
gscv = GridSearchCV(rr, param_grid=params, cv=5, scoring='neg_mean_squared_error')
gscv.fit(xtrain, ytrain)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7....
       93.6, 93.7, 93.8, 93.9, 94. , 94.1, 94.2, 94.3, 94.4, 94.5, 94.6,
       94.7, 94.8, 94.9, 95. , 95.1, 95.2, 95.3, 95.4, 95.5, 95.6, 95.7,
       95.8, 95.9, 96. , 96.1, 96.2, 96.3, 96.4, 96.5, 96.6, 96.7, 96.8,
       96.9, 97. , 97.1, 97.2, 97.3, 97.4, 97.5, 97.6, 97.7, 97.8, 97.9,
       98. , 98.1, 98.2, 98.3, 98.4, 98.5, 98.6, 98.7, 98.8, 98.9, 99. ,
       99.1, 99.2, 99.3, 99.4, 99.5, 99.6, 99.7, 99.8, 99.9])},
             scoring='neg_mean_squared_error')

In [37]:
gscv.best_params_

{'alpha': 3.3000000000000003}

In [38]:
gscv.best_score_

-19485.69268610116

In [40]:
best_ridge = gscv.best_estimator_
best_ridge

Ridge(alpha=3.3000000000000003)

In [42]:
best_ridge.score(xtrain, ytrain)

0.9916243669101343

In [43]:
best_ridge.score(xtest, ytest)

0.8825351751037068

In [44]:
evaluate_model(xtrain, ytrain, xtest, ytest, best_ridge)

Training Results : 
MSE : 3115.02
RMSE: 55.81
MAE : 42.27
R2  : 0.9916


Testing Results : 
MSE : 27291.18
RMSE: 165.20
MAE : 129.92
R2  : 0.8825


In [45]:
r2_scores = cross_val_score(best_ridge, xtrain, ytrain, cv=5, scoring='r2')
r2_scores

array([0.97100188, 0.96612804, 0.89395975, 0.95530361, 0.9330849 ])

In [46]:
r2_scores.mean()

0.9438956399924485

## Lasso Hyperparameter tuning

In [47]:
from sklearn.linear_model import Lasso

In [48]:
ls = Lasso()
gscv2 = GridSearchCV(ls, param_grid=params, cv=5, scoring='neg_mean_squared_error')
gscv2.fit(xtrain, ytrain)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.656e+04, tolerance: 2.205e+03
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.652e+03, tolerance: 2.059e+03
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.527e+03, toleranc

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7....
       93.6, 93.7, 93.8, 93.9, 94. , 94.1, 94.2, 94.3, 94.4, 94.5, 94.6,
       94.7, 94.8, 94.9, 95. , 95.1, 95.2, 95.3, 95.4, 95.5, 95.6, 95.7,
       95.8, 95.9, 96. , 96.1, 96.2, 96.3, 96.4, 96.5, 96.6, 96.7, 96.8,
       96.9, 97. , 97.1, 97.2, 97.3, 97.4, 97.5, 97.6, 97.7, 97.8, 97.9,
       98. , 98.1, 98.2, 98.3, 98.4, 98.5, 98.6, 98.7, 98.8, 98.9, 99. ,
       99.1, 99.2, 99.3, 99.4, 99.5, 99.6, 99.7, 99.8, 99.9])},
             scoring='neg_mean_squared_error')

In [49]:
gscv2.best_params_

{'alpha': 4.7}

In [50]:
gscv2.best_score_

-20339.424655870556

In [51]:
best_lasso = gscv2.best_estimator_
best_lasso

Lasso(alpha=4.7)

In [52]:
best_lasso.score(xtrain, ytrain)

0.971407367759945

In [53]:
best_lasso.score(xtest, ytest)

0.867701955453507

In [54]:
evaluate_model(xtrain, ytrain, xtest, ytest, best_lasso)

Training Results : 
MSE : 10634.03
RMSE: 103.12
MAE : 82.63
R2  : 0.9714


Testing Results : 
MSE : 30737.45
RMSE: 175.32
MAE : 132.42
R2  : 0.8677


In [55]:
r2_scores2 = cross_val_score(best_lasso, xtrain, ytrain, cv=5, scoring='r2')
r2_scores2.mean()

0.9409339519223071

## Selecting ridge model because of highest test r2 score

## make use of ridge for final predictions

In [56]:
ypred_tr = best_ridge.predict(xtrain)
ypred_ts = best_ridge.predict(xtest)

In [57]:
ypred_tr[0:5]

array([[3026.59948831],
       [2477.65873578],
       [3510.02215448],
       [3523.16230693],
       [3078.93839347]])

In [58]:
ytrain.head()

Weight
42    3040
53    2440
21    3570
6     3470
26    3080

In [59]:
ypred_ts[0:5]

array([[2900.55862069],
       [3168.8632676 ],
       [3576.33227981],
       [3984.44889469],
       [3475.47249895]])

In [60]:
ytest.head()

Weight
34    2710
90    2810
3     3405
35    3735
19    3515

## Predicting out of sample values

In [61]:
xnew = pd.read_csv('sample.csv')
xnew

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Audi      100  Midsize       30.8   37.7       44.6        19   
1      Pontiac  Sunbird  Compact        9.4   11.1       12.8        23   
2    Chevrolet   Lumina  Midsize       13.4   15.9       18.4        21   
3        Mazda     RX-7   Sporty       32.5   32.5       32.5        17   
4   Volkswagen      Fox    Small        8.7    9.1        9.5        25   

   MPG.highway      AirBags DriveTrain  ... Fuel.tank.capacity  Passengers  \
0           26          NaN      Front  ...               21.1           6   
1           31          NaN      Front  ...               15.2           5   
2           29          NaN      Front  ...               16.5           6   
3           25  Driver only       Rear  ...               20.0           2   
4           33          NaN      Front  ...               12.4           4   

   Length  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0     193        106     65          37            31.0          17.0   
1     181        101     66          39            25.0          13.0   
2     198        108     71          40            28.5          16.0   
3     169         96     69          37             NaN           NaN   
4     163         93     63          34            26.0          10.0   

    Origin              Make  
0  non-USA          Audi 100  
1      USA   Pontiac Sunbird  
2      USA  Chevrolet Lumina  
3  non-USA        Mazda RX-7  
4  non-USA    Volkswagen Fox  

[5 rows x 26 columns]

## Apply pre.transform on out of sample data

In [63]:
xnew_pre = pre.transform(xnew).toarray()
xnew_pre

array([[ 1.57194871,  1.89337432,  2.06919057, ...,  0.        ,
         0.        ,  0.        ],
       [-0.88813804, -0.87533727, -0.829362  , ...,  0.        ,
         0.        ,  0.        ],
       [-0.42830874, -0.37572014, -0.31892507, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.76737617,  1.35212243,  0.9662822 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.96860817, -1.08351107, -1.1301552 , ...,  0.        ,
         0.        ,  0.        ]])

In [64]:
xnew_pre = pd.DataFrame(xnew_pre, columns=cols)
xnew_pre

num__Min.Price  num__Price  num__Max.Price  num__MPG.city  \
0        1.571949    1.893374        2.069191      -0.602126   
1       -0.888138   -0.875337       -0.829362       0.113500   
2       -0.428309   -0.375720       -0.318925      -0.244313   
3        1.767376    1.352122        0.966282      -0.959938   
4       -0.968608   -1.083511       -1.130155       0.471312   

   num__MPG.highway  num__EngineSize  num__Horsepower  num__RPM  \
0         -0.581941         0.128186         0.540813  0.369586   
1          0.360925        -0.647181        -0.649388 -0.135877   
2         -0.016221        -0.453339        -0.649388 -0.135877   
3         -0.770514        -1.325626         2.134145  2.054464   
4          0.738071        -0.841022        -1.206095  0.369586   

   num__Rev.per.mile  num__Fuel.tank.capacity  ...  cat__Make_Toyota Camry  \
0           0.410659                 1.359872  ...                     0.0   
1           0.673908                -0.449005  ...                     0.0   
2           0.532158                -0.050439  ...                     0.0   
3          -0.014589                 1.022624  ...                     0.0   
4           0.441034                -1.307455  ...                     0.0   

   cat__Make_Toyota Celica  cat__Make_Toyota Previa  cat__Make_Toyota Tercel  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   cat__Make_Volkswagen Corrado  cat__Make_Volkswagen Eurovan  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   cat__Make_Volkswagen Fox  cat__Make_Volkswagen Passat  cat__Make_Volvo 240  \
0                       0.0                          0.0                  0.0   
1                       0.0                          0.0                  0.0   
2                       0.0                          0.0                  0.0   
3                       0.0                          0.0                  0.0   
4                       1.0                          0.0                  0.0   

   cat__Make_Volvo 850  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  

[5 rows x 256 columns]

In [66]:
preds = best_ridge.predict(xnew_pre)
preds

array([[3512.95021948],
       [2661.37717087],
       [3077.43915676],
       [3255.25113905],
       [2245.19394027]])

## Save predictions in dataframe

In [67]:
xnew['Weight_pred'] = preds
xnew

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Audi      100  Midsize       30.8   37.7       44.6        19   
1      Pontiac  Sunbird  Compact        9.4   11.1       12.8        23   
2    Chevrolet   Lumina  Midsize       13.4   15.9       18.4        21   
3        Mazda     RX-7   Sporty       32.5   32.5       32.5        17   
4   Volkswagen      Fox    Small        8.7    9.1        9.5        25   

   MPG.highway      AirBags DriveTrain  ... Passengers  Length  Wheelbase  \
0           26          NaN      Front  ...          6     193        106   
1           31          NaN      Front  ...          5     181        101   
2           29          NaN      Front  ...          6     198        108   
3           25  Driver only       Rear  ...          2     169         96   
4           33          NaN      Front  ...          4     163         93   

   Width  Turn.circle Rear.seat.room  Luggage.room   Origin              Make  \
0     65           37           31.0          17.0  non-USA          Audi 100   
1     66           39           25.0          13.0      USA   Pontiac Sunbird   
2     71           40           28.5          16.0      USA  Chevrolet Lumina   
3     69           37            NaN           NaN  non-USA        Mazda RX-7   
4     63           34           26.0          10.0  non-USA    Volkswagen Fox   

   Weight_pred  
0  3512.950219  
1  2661.377171  
2  3077.439157  
3  3255.251139  
4  2245.193940  

[5 rows x 27 columns]

## save the file to csv

In [68]:
xnew.to_csv('TuningResults.csv', index=False)

## Categorical pipeline

In [69]:
cat_pipe2 = Pipeline(steps=[('imputer', SimpleImputer(strategy='constant', fill_value='unknown')),
                            ('ohe', OneHotEncoder(handle_unknown='ignore'))])